### ISSUE TITLE
API function that returns metadata for a given branch

### ISSUE THREAD

**Issue by balsa-sarenac** [openlawlibrary/taf#324]
This is a feature request:

It would be nice if the API would be extended with a function that returns metadata for any branch (not just publication).

**Comment by renatav** [comment]
The reason why TAF does not already provide such a function is because we only validate branches if the authentication repository's main branch contains information about them. Our build process creates branches that can only be validated after merge (that is when we sign snapshot and targets). We had some short discussions about other branches with NYU and Justin, but we are not close to being able to handle them it TAF. Until we figure all of that out, I'd prefer to implement this in platform, in an authentication repository class which extends TAF's authentication repository.

**Comment by renatav** [comment]
I've been thinking about this and I don't think that TAF should be responsible for returning information about branches that are not listed in target files. I'll close this issue, but let's discuss if a similar requirement pops up in the future
