### ISSUE TITLE
Configure verbosity to updater output with -v and -vv

### ISSUE THREAD

**Issue by n-dusan** [openlawlibrary/taf#396]
Not all information shown in output for updater is important. Select only the most important messages for updater and show these, while the other suppressed messages are only shown with -v, or -vv flags

**Comment by renatav** [comment]
I've been trying to use different log levels to separate more and less important information. We should be just able to set the debug level.  What that is currently being shown is not important? I thought it made sense to log every step, so that running the updater looks like an installation, where you always know what is happening. So, to me it made sense to print something like "Checking if all existing target repositories are clean..". We could only leave things like "Cloned repository", "Validated repository", "Merged" and error message if it occurs. In that case, we should go over log levels and update where necessary. That being said, there are a lot more messages that are currently hidden, so maybe we can leverage some to a level above info and show the current trace if `-v` flag is provided. Thoughts?
