### ISSUE TITLE
Transition to `yubikey-manager` 5.x

### ISSUE THREAD

**Issue by n-dusan** [openlawlibrary/taf#410]
I couldn't sign a repository using YubiKey 5C with `yubikey-manager` 4.0.9. 
Look into upgrading our `cryptography` dependency as well

**Comment by Rana-KV** [comment]
Hi @n-dusan,

I've noticed that updating to YubiKey Manager 5.x introduces significant changes to the project due to deprecated functions and module restructuring. For example, `connect_to_device` from ykman.device no longer exists. Adapting the code to support YubiKey Manager 5.x would make it incompatible with previous versions of the project.

One approach to address this could be to check the version numbers and update the code to work with both versions, although this might be less efficient. This would ensure backward compatibility while taking advantage of the new functionalities provided by YubiKey Manager 5.x.

Let me know your thoughts on this or if you have any other suggestions.

**Comment by renatav** [comment]
@Rana-KV Thanks for looking into this issue, this is currently a priority for us. I don't think that backward compatibility is something we need to worry about here. We have API functions for signing and setting up YubiKeys, so no one should be using any of the impacted code directly. The reason why we need the do this is because we recelty received a donation of new 20 YubiKeys from Yubico and we can't use them. We only need to make sure that you'll still be able to sign with an older YubiKey after the update, so we'll need to test that before merging
